name: Run GCOV

on:
  push:

jobs:
  run-gcov:
    name: '${{ matrix.os }}'
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04]

    steps:
      - name: Check out repository
        uses: actions/checkout@v4 
        with:
          ref: 576e7552a29e30b40205f81f2ff4d461f018313f

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          
      - name: Install dependencies for project (Linux)
        if: runner.os == 'Linux'
        run: | 
          sudo apt-get update
          sudo apt-get install -y ffmpeg libsdl2-2.0-0 adb libusb-1.0-0 gcc git pkg-config meson ninja-build libsdl2-dev \
                 libavcodec-dev libavdevice-dev libavformat-dev libavutil-dev \
                 libswresample-dev libusb-1.0-0-dev android-sdk
          export ANDROID_SDK_ROOT=~/Android/Sdk
          
      - name: Build repository 
        run: | 
          export CC=gcc
          export CXX=g++
          export CFLAGS="-fprofile-arcs -ftest-coverage -fPIC"
          export LDFLAGS="-fprofile-arcs -ftest-coverage -fPIC"
          meson setup x --buildtype=release --strip -Db_lto=true
          ninja -Cx
          
      - name: Run GCOV
        run: |
          #!/bin/bash
          set +e 

          mkdir gcovlogs
          echo "=========[GCOV Service Started!]========="

          DIRECTORY=.

          is_executable() {
            local file="$1"
            if file "$file" | grep -q 'ELF 64-bit'; then
              return 0
            else
              return 1
            fi
          }

          run_with_gcov() {
            local executable="$1"
            output="$("$executable" 2>/dev/null)"  # Suppress stderr
            local exit_status=$?
            
            if [ $exit_status -eq 124 ]; then
              echo "Command timed out after 10 seconds: $executable"
              return  # Skip gcov analysis on timeout
            fi
            
            gcov --all-blocks --branch-probabilities --branch-counts --function-summaries -H --use-colors --demangled-names --stdout --unconditional-branches --verbose "$executable" > ./gcovlogs/"$executable".gcov.log
          }

          find "$DIRECTORY" -type f -executable | while read -r file; do
            if is_executable "$file"; then
              run_with_gcov "$file"
              echo ""
              echo "" 
              echo "" 
            fi
          done

          echo "=========[GCOV service finished]========="
  
      - name: Upload GCOV reports
        uses: actions/upload-artifact@v4
        with:
          name: gcov-report-${{ github.event.repository.name }}-on-${{ matrix.os }}
          path: './gcovlogs/*'
