name: Run ThreadSanitizer

on:
  push:

jobs:
  run-tsan:
    name: '${{ matrix.os }}'
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04]

    steps:
      - name: Check out repository
        uses: actions/checkout@v2 
        with:
          ref: 576e7552a29e30b40205f81f2ff4d461f018313f

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
        
      - name: Install dependencies for project
        run: | 
          sudo apt-get update
          sudo apt-get install -y ffmpeg libsdl2-2.0-0 adb libusb-1.0-0 gcc git pkg-config meson ninja-build libsdl2-dev \
                 libavcodec-dev libavdevice-dev libavformat-dev libavutil-dev \
                 libswresample-dev libusb-1.0-0-dev android-sdk
          export ANDROID_SDK_ROOT=~/Android/Sdk
          
      - name: Build repository 
        run: | 
          meson setup x --buildtype=release --strip -Db_lto=true
          ninja -Cx

      - name: Install ThreadSanitizer dependencies (Linux)
        if: runner.os == 'Linux'
        run: sudo apt-get install -y clang-14 libclang-14-dev llvm-14 llvm-14-dev llvm-14-tools llvm-14-linker-tools
      
      - name: Run Google Thread Sanitizer (source code) (Linux)
        if: runner.os == 'Linux'
        run: |
            #!/bin/bash
            set +e

            files=$(find . -type f)
            TIMEOUT_DURATION=10

            for file in $files; do
                if [[ "$file" == *.c || "$file" == *.cpp ]]; then
                    include_dirs=$(find . -name '*.h' -exec dirname {} + | sort -u | sed 's/^/-I /')
                    if ! timeout 60 clang -I "$include_dirs" -fsanitize=thread -fPIE -pie -O2  -g "$file" -o ./compiled.out > /dev/null 2> /tmp/clang_errors.txt; then
                        exit_code=$?
                        if [ $exit_code -eq 1 ]; then
                            continue
                        fi
                        continue 
                    fi

                    timeout $TIMEOUT_DURATION ./compiled.out
                    rm -f ./compiled.out
                fi
            done
